name = "tesss"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[router]]
pattern = "enduk.us.kg"
custom_domain = true

[vars]
PROXYIP = "35.219.50.99:443"
UUID = "66a2450b-61d3-445f-809a-f13ac290f652"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
