name = "ehgu"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:443"
UUID = "f5e2b683-ff00-4086-923a-eb8f6ef24401"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
